export const REPUTATION_POINTS = {
  PAPER_ACCEPTED_LOW: 5,
  PAPER_ACCEPTED_MID: 10,
  PAPER_ACCEPTED_HIGH: 15,
  REVIEW_SUBMITTED: 5,
  ENDORSEMENT_RECEIVED: 8,
  ENDORSEMENT_GIVEN: 3,
  BOUNTY_REVIEW_COMPLETED: 8,
  PAPER_ENDORSED_BY_TRUSTED: 20,
} as const;

export const REPUTATION_THRESHOLDS = {
  CAN_ENDORSE: 100,
  TRUSTED_REVIEWER: 500,
  CAN_MODERATE: 1000,
} as const;

export type ReputationEventType = keyof typeof REPUTATION_POINTS;
